image: ubuntu:rolling

variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - build

.install_template: &install_dependencies
  before_script:
      # Install build dependencies.
    - apt-get update
    - apt-get install -y -qq build-essential wget curl
    #- apt-get install -y -qq texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-xetex

      # default pandoc is too old -> install a newer version manually
    - PANDOC_VERSION="2.14.2"
    - pandoc_deb="pandoc-${PANDOC_VERSION}-1-amd64.deb"
    - wget "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${pandoc_deb}"
    - dpkg -i ${pandoc_deb}
    - rm ${pandoc_deb}

      # default textlife from apt-get is too old
      # install the latest texlife version manually
    - REMOTE="http://mirror.ctan.org/systems/texlive/tlnet"
    - INSTALL="/tmp/install-texlive"
    - mkdir -p $INSTALL
    - curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL --strip-components=1
    - $INSTALL/install-tl -no-gui -profile .texlife.profile
    - VERSION=$($INSTALL/install-tl --version | grep 'version' | grep -o '[0-9]\{4\}')
    - PLATFORM=$($INSTALL/install-tl --print-platform)
    - TEXLIVE_DIR="/usr/local/texlive/${VERSION}"
    - TEXBIN="/usr/local/texlive/${VERSION}/bin/${PLATFORM}"
    - export "PATH=$TEXBIN:$PATH"

      # initialization for tlmgr
    - apt-get install xzdec
    - tlmgr init-usertree

      # packages specified in the template
    - tlmgr install adjustbox background bidi csquotes footmisc footnotebackref fvextra mdframed pagecolor sourcecodepro sourcesanspro titling ulem upquote xurl

    # trial and error
    - tlmgr install letltxmacro zref everypage framed collectbox

    # packages needed for the template
    - tlmgr install xecjk filehook unicode-math ucharcat pagecolor babel-german ly1 mweights sourcecodepro sourcesanspro mdframed needspace fvextra footmisc footnotebackref background



build_pdf:
  <<: *install_dependencies
  stage: build
  script:
    - make pdf
  artifacts:
    when: on_success
    name: pdf
    paths:
      - build/*.pdf

